### ISSUE TITLE
CallBackNum issue

### ISSUE THREAD

**Issue by UncleTedd** [pruiz/AberrantSMPP#30]
Tried to create a SmppSubmitSm and set all the needed values to it, i didnt need callbacknum but it kept giving me this error: "ERROR - Send error: callback_num size must be between 4 and 19 characters." so i tried to add it, used different encodings to get the bytes of that string but the issue didnt go away. Tried to fill other callbacknum fields but still the issue didnt go away. Any suggestions on what to do?

**Comment by UncleTedd** [comment]
var submitSm = new SmppSubmitSm
            {
                CommandStatus = CommandStatus.ESME_ROK,
                SourceAddressTon = Pdu.TonType.Alphanumeric,
                SourceAddressNpi = Pdu.NpiType.Unknown,
                SourceAddress = from,
                DataCoding = DataCoding.UCS2,
                PriorityFlag = Pdu.PriorityType.Lowest,
                ShortMessage = message,
                DestinationAddressTon = Pdu.TonType.International,
                DestinationAddressNpi = Pdu.NpiType.ISDN,
                DestinationAddress = to,
                CallbackNum = callbackNumBytes,
                CallbackNumPresInd = 0x01,
                CallbackNumAtag = callbackNumAtag
            };

**Comment by pruiz** [comment]
Hi,

What are you passing as 'callbackNumBytes'..

Regards
Pablo

**Comment by UncleTedd** [comment]
Hi. i was passing 12345 as an example. I passes null and the issue is gone now. Now i am facing a different issue. Client has a Start() method and this method has autoconnection handler or so, when i call Start(), i get this,Client isStarted is : True. Then i call Connect() and it throws something like you cant explicitly call connect when the autoconnection handler is on. But the state of the connection is : INFO  - Client state is : Inactive When i try to call Bind(),  it throws this : Connection error: Can't bind non-connected client, call ConnectAsync() first.

**Comment by pruiz** [comment]
Start is meant to try to connect automatically (and retry periodically if
failed or connection dropped).  However, if manual connection handling is
intended, the Connect method can be used instead. But using both at the
same time is not allowed.

**Comment by UncleTedd** [comment]
Appreciate your help Pablo. I used start(), and i get this error : NFO  - Client isStarted is : False
2024-10-17 10:54:48,908 INFO  - Client state is : Inactive
2024-10-17 10:54:48,909 ERROR - Connection error: Can't bind non-connected client, call ConnectAsync() first.
2024-10-17 10:54:48,914 ERROR - Detailed Exception: System.InvalidOperationException: Can't bind non-connected client, call ConnectAsync() first.
   at AberrantSMPP.Utility.GuardEx.Against(Boolean invalid, String message, String caller)
   at AberrantSMPP.SMPPClient.Bind(). I used Inetlab and it worked just fine. i wonder what could the issue be?

**Comment by pruiz** [comment]
"Client state is: Inactive" means the SMPPClient is not able to connect to
the smpp server. Please review connection details (like host/ip, port,
credentials, etc.)

Also, you can hook up connection callback delegates to get information
about connecting errors..

**Comment by UncleTedd** [comment]
I am sorry if i am being anooying, but would you please take a look at how i create the client? Because i am getting the same error.
_client = new SMPPClient(host, port)
        {
            SystemId = _systemId,
            Password = _password,
            NpiType = Pdu.NpiType.Unknown,
            TonType = Pdu.TonType.Alphanumeric,
        };
Error i am getting is :
Client state changed to: Connecting
2024-10-17 11:43:14,366 INFO  - Client state changed to: Inactive
2024-10-17 11:43:14,367 ERROR - Connection error: System.AggregateException: One or more errors occurred. (Name or service not known)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(IPAddress address, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_1(Object s, ValueStopwatch stopwatch)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DotNetty.Transport.Bootstrapping.DefaultNameResolver.ResolveAsync(EndPoint address)
   at DotNetty.Transport.Bootstrapping.Bootstrap.DoResolveAndConnectAsync(EndPoint remoteAddress, EndPoint localAddress)
   at DotNetty.Transport.Bootstrapping.Bootstrap.DoResolveAndConnectAsync(EndPoint remoteAddress, EndPoint localAddress)

**Comment by pruiz** [comment]
From the 'Name or service not known' looks like the hostname specified as
'host' on SMPPClient's ctor is not a valid hostname (ie. cannot be resolved
by dns).

**Comment by UncleTedd** [comment]
I get this, but when i try to use Inetlabs smpp and pass the same IP and Ports it connects with no problem. What could the problem be?

**Comment by pruiz** [comment]
Not sure.. what are you actually passing as 'host'?

**Comment by UncleTedd** [comment]
as host i am passing the ip of the smsc server

**Comment by UncleTedd** [comment]
i am able to connect to the server using telnet

**Comment by pruiz** [comment]
may you share a full excerpt of the failing code?

**Comment by UncleTedd** [comment]
Sure!


private Task<bool> ConnectAsyncOld()
    {
        try
        {
            if (_isConnected) return Task.FromResult(true);

            _log.Info($"Attempting to connect to SMSC: {_client.Host}:{_client.Port}");
            _log.Info($"Client isStarted is : {_client.Started}");
            _client.Start();
            _log.Info($"Client state is : {_client.State}");
            _isConnected = true;
            _log.Info($"Client state is : {_client.State}");
            return Task.FromResult(true);
        }
        catch (Exception ex)
        {
            _log.Error($"Connection error: {ex.Message}");
            _log.Error($"Detailed Exception: {ex.StackTrace}");
            _isConnected = false;
            return Task.FromResult(false);
        }
    }

    public async Task<bool> SendSmsAsync(string to, string from, string message)
    {
        try
        {
            var started = await ConnectAsyncOld();
            if (started)  _log.Info($"Client State is {_client.State}"); 
            
            var submitSm = new SmppSubmitSm
            {
                CommandStatus = CommandStatus.ESME_ROK,
                SourceAddressTon = Pdu.TonType.Alphanumeric,
                SourceAddressNpi = Pdu.NpiType.Unknown,
                SourceAddress = from,
                DataCoding = DataCoding.UCS2,
                PriorityFlag = Pdu.PriorityType.Lowest,
                ShortMessage = message,
                DestinationAddressTon = Pdu.TonType.International,
                DestinationAddressNpi = Pdu.NpiType.ISDN,
                DestinationAddress = to.Replace("+", ""),
                CallbackNum = null
            };

            _log.Info($"Sending SMS: {JsonConvert.SerializeObject(submitSm)}");

            var response = _client.SendPdu(submitSm);
            _log.Info($"Response from send SMS is: {response}");

            if (response > 0)
            {
                _log.Info("Message sent successfully.");
                return true;
            }

            _log.Error("Failed to send message. Status: " + response);
            return false;
        }
        catch (Exception ex)
        {
            _log.Error($"Send error: {ex.Message}");
            return false;
        }
    }

**Comment by UncleTedd** [comment]
Hi Pablo.
Any suggestions on how to connect properly?
